init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: env
- sh: echo $PATH | tr ':' '\n'
- sh: cat /etc/network/interfaces
- sh: ls -ltr /etc/network/interfaces.d/
- sh: ip -o -4 addr show up primary scope global | ( read -r num dev fam addr rest; echo ${addr%/*}; )
- sh: cat /etc/hosts


clone_script:
- pwsh: |
    Write-host "PowerShell Core version $($PSVersionTable.PSVersion)"
    if ($PSVersionTable.PSVersion.Major -le 5) {throw "PowerShell version is less or equel than 5. Should be at least 6 when called from -pwsh prefix"}
- pwsh -command '"Hello World"'
- sh: pwsh -command '"Hello World"'


build: off
test: off
